### ISSUE TITLE
Flickering test: ./spec/features/comments_spec.rb:

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/travel-support-program#95]
Some of the comments tests are failing randomly. It would be worth to figure out what is causing this and fix it.

Some examples of the failures:

https://travis-ci.org/openSUSE/travel-support-program/builds/250002116
https://travis-ci.org/openSUSE/travel-support-program/builds/248344701

======
```
  1) Comments  Add private comment

     Failure/Error: page.should have_content 'history'

       expected to find text "history" in "Demo Travel Support Program Signed in as commanderlajaier Log out OPTIONS User guide Events Your profile Travel support requests Reimbursements Shipment requests Budgets Travel expenses report EXTERNAL LINKS openSUSE TSP Application's Github travel support requests > travel support request #543182455 ×Comment added. travel support request #543182455 canceled (no more actions allowed) The request have been canceled and cannot be longer modified. Battle of Yavin (since 2017-07-02 at US) red_two subject description estimated approved Gas EUR70.00 EUR40.00 30 days ago red_two changed the state from incomplete to submitted. 30 days ago commanderlajaier changed the state from submitted to canceled. less than a minute ago commanderlajaier wrote a comment. I don't like this guy, but don't tell him. Add comment Version 1.1.7"

     # ./spec/features/comments_spec.rb:56:in `block (2 levels) in <top (required)>'

  2) Comments  Add comment as requester

     Failure/Error: page.should have_content 'history'

       expected to find text "history" in "Demo Travel Support Program Signed in as red_two Log out OPTIONS User guide Events Your profile Travel support requests Reimbursements Shipment requests Travel expenses report EXTERNAL LINKS openSUSE TSP Application's Github travel support requests > travel support request #543182455 ×Comment added. travel support request #543182455 canceled (no more actions allowed) The request have been canceled and cannot be longer modified. Battle of Yavin (since 2017-07-02 at US) red_two subject description estimated approved Gas EUR70.00 EUR40.00 30 days ago red_two changed the state from incomplete to submitted. 30 days ago commanderlajaier changed the state from submitted to canceled. less than a minute ago red_two wrote a comment. Luke always get all the money. That's unfair. Add comment Version 1.1.7"

     # ./spec/features/comments_spec.rb:34:in `block (2 levels) in <top (required)>'

```

**Comment by ancorgs** [comment]
I have not seen this happening recently in Travis, in any of my local builds or in any of the three docker containers we currently offer for development (sqlite3, PostgreSQL and Mariadb). I guess it got fixed by any of the recent pull requests.
